#Turn off laptop screen
#monitor=eDP-2,disable
#monitor=eDP-1,disable

#native laptop resolution
monitor=eDP-1,preferred,auto,auto
monitor=eDP-0,preferred,auto,auto

#Reduce laptop resolution
#monitor=eDP-2,1920x1200@120,auto,1.333
#monitor=eDP-1,1920x1200@120,auto,1.333

#For DP monitor 
monitor=DP-3,3840x2160@120,auto,1.666
monitor=DP-1,3840x2160@240,auto,1.666
#monitor=DP-1,3440x1440@100,auto,1.25 #21:9
#monitor=DP-3,3440x1440@100,auto,1.25 #21:9

#For HDMI monitor
#monitor=HDMI-A-1,preferred,auto,1.0

#turn off everything
#monitor=eDP-2,disable
#monitor=eDP-1,disable
#monitor=DP-3,disable
#monitor=DP-1,disable
#monitor=HDMI-A-1,disable

misc {
    mouse_move_enables_dpms = true
    key_press_enables_dpms = true
}

