return {
  'neovim/nvim-lspconfig',
  dependencies = {
    'j-hui/fidget.nvim',
  },
}
-- return {
--   'neovim/nvim-lspconfig',
--   dependencies = {
--     { 'mason-org/mason.nvim', opts = {} },
--     'mason-org/mason-lspconfig.nvim',
--     'WhoIsSethDaniel/mason-tool-installer.nvim',
--   },
--   config = function()
--     vim.api.nvim_create_autocmd('LspAttach', {
--       group = vim.api.nvim_create_augroup('kickstart-lsp-attach', { clear = true }),
--       callback = function(event)
--         local map = function(keys, func, desc, mode)
--           mode = mode or 'n'
--           vim.keymap.set(mode, keys, func, { buffer = event.buf, desc = 'LSP: ' .. desc })
--         end
--         map('cd', vim.lsp.buf.rename, '[C]hange [D]efinition')
--
--         map('g.', vim.lsp.buf.code_action, '[G]oto code actions', { 'n', 'x' })
--
--         map('gu', require('snacks').picker.lsp_references, '[G]oto [U]sages')
--         map('gI', require('snacks').picker.lsp_implementations, '[G]oto [I]mplementation')
--
--         map('gd', require('snacks').picker.lsp_definitions, '[G]oto [D]efinition')
--         map('gD', vim.lsp.buf.declaration, '[G]oto [D]eclaration')
--
--         map('gO', require('snacks').picker.lsp_symbols, 'Open Document Symbols')
--         map('<C-t>', require('snacks').picker.lsp_symbols, 'Open Document Symbols')
--         map('gW', require('snacks').picker.lsp_workspace_symbols, 'Open Workspace Symbols')
--
--         map('grt', require('snacks').picker.lsp_type_definitions, '[G]oto [T]ype Definition')
--
--         local client = vim.lsp.get_client_by_id(event.data.client_id)
--         if client and client:supports_method(vim.lsp.protocol.Methods.textDocument_documentHighlight, event.buf) then
--           local highlight_augroup = vim.api.nvim_create_augroup('kickstart-lsp-highlight', { clear = false })
--           vim.api.nvim_create_autocmd({ 'CursorHold', 'CursorHoldI' }, {
--             buffer = event.buf,
--             group = highlight_augroup,
--             callback = vim.lsp.buf.document_highlight,
--           })
--
--           vim.api.nvim_create_autocmd({ 'CursorMoved', 'CursorMovedI' }, {
--             buffer = event.buf,
--             group = highlight_augroup,
--             callback = vim.lsp.buf.clear_references,
--           })
--
--           vim.api.nvim_create_autocmd('LspDetach', {
--             group = vim.api.nvim_create_augroup('kickstart-lsp-detach', { clear = true }),
--             callback = function(event2)
--               vim.lsp.buf.clear_references()
--               vim.api.nvim_clear_autocmds { group = 'kickstart-lsp-highlight', buffer = event2.buf }
--             end,
--           })
--         end
--
--         if client and client:supports_method(vim.lsp.protocol.Methods.textDocument_inlayHint, event.buf) then
--           map('<leader>th', function()
--             vim.lsp.inlay_hint.enable(not vim.lsp.inlay_hint.is_enabled { bufnr = event.buf })
--           end, '[T]oggle Inlay [H]ints')
--         end
--       end,
--     })
--
--     vim.diagnostic.config {
--       severity_sort = true,
--       float = { border = 'rounded', source = 'if_many' },
--       signs = vim.g.have_nerd_font and {
--         text = {
--           [vim.diagnostic.severity.ERROR] = '󰅚 ',
--           [vim.diagnostic.severity.WARN] = '󰀪 ',
--           [vim.diagnostic.severity.INFO] = '󰋽 ',
--           [vim.diagnostic.severity.HINT] = '󰌶 ',
--         },
--       } or {},
--       virtual_text = {
--         source = 'if_many',
--         spacing = 2,
--         format = function(diagnostic)
--           local diagnostic_message = {
--             [vim.diagnostic.severity.ERROR] = diagnostic.message,
--             [vim.diagnostic.severity.WARN] = diagnostic.message,
--             [vim.diagnostic.severity.INFO] = diagnostic.message,
--             [vim.diagnostic.severity.HINT] = diagnostic.message,
--           }
--           return diagnostic_message[diagnostic.severity]
--         end,
--       },
--     }
--
--     -- Add any additional override configuration in the following tables. Available keys are:
--     -- - cmd (table): Override the default command used to start the server
--     -- - filetypes (table): Override the default list of associated filetypes for the server
--     -- - capabilities (table): Override fields in capabilities. Can be used to disable certain LSP features.
--     -- - settings (table): Override the default settings passed when initializing the server.
--     --       For example, to see the options for `lua_ls`, you could go to: https://luals.github.io/wiki/settings/
--     local servers = {
--       pyrefly = {},
--       ty = {},
--       cssls = {},
--       clangd = {},
--       ruff = {},
--       vtsls = {},
--       html = {},
--       astro = {},
--       emmet_language_server = {},
--       tailwindcss = {},
--       jdtls = {},
--       texlab = {},
--       lua_ls = {
--         settings = {
--           Lua = {
--             completion = {
--               callSnippet = 'Replace',
--             },
--             -- You can toggle below to ignore Lua_LS's noisy `missing-fields` warnings
--             diagnostics = { disable = { 'missing-fields' } },
--           },
--         },
--       },
--       harper_ls = {
--         filetypes = { 'markdown', 'html', 'typst' },
--       },
--     }
--     local ensure_installed = vim.tbl_keys(servers or {})
--     vim.list_extend(ensure_installed, {
--       'stylua',
--     })
--     require('mason-tool-installer').setup { ensure_installed = ensure_installed, run_on_start = false }
--
--     for server_name, config in pairs(servers) do
--       vim.lsp.config(server_name, config)
--       vim.lsp.enable(server_name)
--     end
--   end,
-- }
